# Generated by Django 3.2.6 on 2021-08-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_remove_emolyees_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='participant',
            new_name='participants',
        ),
    ]
