# Generated by Django 3.2.6 on 2021-08-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emolyees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=14, unique=True)),
                ('name', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField(unique=True)),
                ('bio', models.TextField(max_length=2000)),
                ('experiance', models.CharField(choices=[('JONIOR', 'Jonior'), ('MID', 'Mid-level'), ('SENIOR', 'Senior')], max_length=6)),
            ],
        ),
    ]
